# gem 'rack-attack'

source 'https://rubygems.org'

gem 'rails', '5.0.2'
gem 'rack'
gem 'rack-cors', '1.0.2', require: 'rack/cors'
gem 'rack-protection', '2.0.1'
gem 'rack-proxy', '0.6.1'
gem 'rack-test', '0.6.3'
gem 'rack-throttle', '0.5.0'
gem 'execjs'
